-- local keymap = require("lz.n").keymap({
--     "nvim-tree",
--     cmd = "NvimTreeToggle",
--     after = function ()
--         require("nvim-tree").setup({})
--     end,
-- })
--
-- keymap.set("n", "<C-n>", function ()
--     require("nvim-tree").setup({})
-- end)
--
-- require("lz.n").load {
--     {
--         "nvim-tree.nvim",
--         keys = {
--             { "<C-n>", "<CMD>NvimTreeToggle<CR>", desc = "File" },
--         },
--         after = function ()
--             require("nvim-tree").setup({})
--         end,
--     }
-- }
